
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up Maven Configuration
        run: echo "<settings><servers><server><id>easy-weprogram</id><username>1919022585@qq.com</username><password>$GITHUB_TOKEN</password></server></servers><profiles><profile><id>rainyblossom</id><repositories><repository><id>central</id><url>https://repo1.maven.org/maven2</url><releases><enabled>true</enabled></releases><snapshots><enabled>true</enabled></snapshots></repository><repository><id>easy-weprogram</id><name>easy weprogram</name><url>https://maven.pkg.github.com/easy-utils/easy-weprogram</url></repository></repositories></profile></profiles><activeProfiles><activeProfile>rainyblossom</activeProfile></activeProfiles></settings>" > ~/.m2/settings.xml
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -Dregistry=https://maven.pkg.github.com/easy-utils/easy-weprogram -Dtoken=$GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ github.token }}
